### ISSUE TITLE
Providing a license for this repo?

### ISSUE THREAD

**Issue by TysonAndre** [javazac/filter_var#8]
I haven't seen this asked/mentioned before in the issues or pull requests section of this repo, and don't see one in the README or source code after a quick glance

https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/licensing-a-repository

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work. If you're creating an open source project, we strongly encourage you to include an open source license. The Open Source Guide provides additional guidance on choosing the correct license for your project.

**Comment by javazac** [comment]
I had no idea anyone cared enough about this project to want a license. I've added the MIT license. Have fun!
